name: umapns
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=10.2
  - firelight=0.2.1
  - ipykernel
  - jupyter=1.0.0 
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - numba=0.51.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - pandas=1.2.2
  - pip=20.3.3
  - python=3.8.5
  - pytorch=1.7.1
  - scikit-image=0.16.2
  - scikit-learn=0.23.2
  - scipy=1.6.0
  - setuptools=52.0.0
  - torchaudio=0.7.2
  - torchvision=0.8.2
  - yaml=0.2.5
  - pip:
    - h5py==2.10.0
    - keras-preprocessing==1.1.2
    - pykeops==1.4.2
    - tensorboard==2.4.1
    - tensorflow==2.4.1
    - tqdm==4.60.0
    - umap-learn==0.5.0
